//! The application icon set (issue #34).
//!
//! The icons are generated by `tauri/icons/generate.py` rather than checked in
//! as opaque artwork, so a reviewer can see what they are. That only helps if
//! the generator and the design tokens do not quietly drift apart, which is
//! what this file checks: the script duplicates the palette as Python literals
//! because it cannot import TypeScript, and a duplicated constant with nothing
//! comparing the copies is a constant that will eventually disagree.

use std::{fs, path::Path};

fn repository_root() -> &'static Path {
    Path::new(env!("CARGO_MANIFEST_DIR"))
}

fn read(relative: &str) -> String {
    let path = repository_root().join(relative);
    fs::read_to_string(&path).unwrap_or_else(|error| panic!("{}: {error}", path.display()))
}

/// Every `#rrggbb` in a file, uppercased and without the hash.
fn hex_colours(text: &str) -> Vec<String> {
    text.match_indices('#')
        .filter_map(|(at, _)| text.get(at + 1..at + 7))
        .filter(|candidate| candidate.chars().all(|c| c.is_ascii_hexdigit()))
        .map(|candidate| candidate.to_ascii_uppercase())
        .collect()
}

/// A `(0xAA, 0xBB, 0xCC)` tuple from the generator, as `AABBCC`.
fn python_colour(source: &str, name: &str) -> String {
    let line = source
        .lines()
        .find(|line| line.starts_with(&format!("{name} = (")))
        .unwrap_or_else(|| panic!("the generator defines no {name}"));
    let inside = line
        .split_once('(')
        .and_then(|(_, rest)| rest.split_once(')'))
        .map(|(inside, _)| inside)
        .unwrap_or_default();
    inside
        .split(',')
        .map(|component| {
            let component = component.trim().trim_start_matches("0x");
            format!("{component:0>2}")
        })
        .collect::<Vec<_>>()
        .join("")
        .to_ascii_uppercase()
}

#[test]
fn the_generator_uses_the_same_palette_as_the_design_tokens() {
    let tokens = read("ui/src/tokens.ts");
    let generator = read("tauri/icons/generate.py");
    let in_tokens = hex_colours(&tokens);

    for name in ["BACKGROUND", "FOREGROUND", "ACCENT", "LINE"] {
        let colour = python_colour(&generator, name);
        assert!(
            in_tokens.contains(&colour),
            "the icon generator's {name} (#{colour}) is not in ui/src/tokens.ts — \
             the two copies of the palette have drifted"
        );
    }
}

/// Width and height from a PNG's IHDR, which is always the first chunk.
fn png_dimensions(bytes: &[u8]) -> (u32, u32) {
    assert_eq!(
        &bytes[..8],
        b"\x89PNG\r\n\x1a\n",
        "not a PNG — an icon that is not the format it claims will not load"
    );
    let width = u32::from_be_bytes(bytes[16..20].try_into().unwrap());
    let height = u32::from_be_bytes(bytes[20..24].try_into().unwrap());
    (width, height)
}

#[test]
fn every_icon_is_a_real_png_of_the_size_its_name_promises() {
    for (name, expected) in [
        ("32x32.png", 32),
        ("128x128.png", 128),
        ("128x128@2x.png", 256),
        ("256x256.png", 256),
        ("512x512.png", 512),
        ("icon.png", 512),
    ] {
        let bytes = fs::read(repository_root().join("tauri/icons").join(name))
            .unwrap_or_else(|error| panic!("{name}: {error}"));
        assert_eq!(png_dimensions(&bytes), (expected, expected), "{name}");
    }
}

#[test]
fn the_windows_icon_is_an_ico_holding_several_sizes() {
    // A single-size .ico looks correct in the installer and blurry in the task
    // bar, which is exactly the kind of defect nobody files a bug about.
    let bytes = fs::read(repository_root().join("tauri/icons/icon.ico")).expect("icon.ico");
    assert_eq!(&bytes[..4], &[0, 0, 1, 0], "not an ICO header");

    let count = u16::from_le_bytes([bytes[4], bytes[5]]);
    assert!(count >= 3, "only {count} size(s) in icon.ico");
}

#[test]
fn the_icons_the_bundler_is_told_about_all_exist() {
    // A missing icon fails the build with a proc-macro panic that names the
    // file but not the configuration entry that asked for it.
    let config = read("tauri/tauri.conf.json");
    let configured: serde_json::Value = serde_json::from_str(&config).expect("valid JSON");
    let icons = configured["bundle"]["icon"]
        .as_array()
        .expect("the bundle configuration lists icons");
    assert!(!icons.is_empty());

    for icon in icons {
        let relative = icon.as_str().expect("an icon path");
        let path = repository_root().join("tauri").join(relative);
        assert!(path.exists(), "{relative} is configured but absent");
    }
}
