#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Validation runbook for issue #38 — packaged WPD sync against the AYN Odin 3.
#
# Run this on the Windows host, in Git Bash, with the Odin connected.
#
# MTP is not a filesystem, and this runbook is mostly about the places that
# difference shows: ambiguous names, no atomic publication, session-scoped
# object ids, and a device that can lock itself mid-transfer.

ENV_FILE="${ENV_FILE:-docs/validation/windows-sync-core/odin-wpd-results.env}"
mkdir -p "$(dirname "$ENV_FILE")"

TOTAL_STAGES=8
TOTAL_MINUTES=70

banner "Validate packaged WPD sync on the AYN Odin 3 (#38)"

# ── 1 ────────────────────────────────────────────────────────────────────
stage "Identify the build and host" 5
ask INSTALLER_PATH "Path to the .exe installer under test:"
if [[ -f "$INSTALLER_PATH" ]]; then
  INSTALLER_SHA=$(sha256sum "$INSTALLER_PATH" | cut -d' ' -f1)
  say "sha256: $INSTALLER_SHA"
else
  ask INSTALLER_SHA "Installer sha256:"
fi
ask BUILD_COMMIT "Commit the installer was built from:"
ask WINDOWS_VERSION "Windows version (cmd /c ver):"
write_env INSTALLER_SHA256 "$INSTALLER_SHA"
write_env BUILD_COMMIT "$BUILD_COMMIT"
write_env WINDOWS_VERSION "$WINDOWS_VERSION"

# ── 2 ────────────────────────────────────────────────────────────────────
stage "Identify the device" 8
say "On the Odin: Settings → About."
ask ODIN_MODEL "Model (e.g. Odin 3 Pro):"
ask ANDROID_VERSION "Android version:"
ask FIRMWARE_BUILD "Firmware / build number:"
say "Connect by USB, then pull down the notification shade."
step "Set the USB mode explicitly to File Transfer / MTP."
ask USB_MODE "USB mode selected:"
say "Lock state matters: WPD behaves differently on a locked screen."
ask LOCK_STATE "Screen state during the run (unlocked / locked):"
if confirm "Did Windows prompt you to authorize this computer on the device?"; then
  AUTHORIZED=prompted-and-accepted
else
  AUTHORIZED=no-prompt
fi
write_env ODIN_MODEL "$ODIN_MODEL"
write_env ANDROID_VERSION "$ANDROID_VERSION"
write_env FIRMWARE_BUILD "$FIRMWARE_BUILD"
write_env USB_MODE "$USB_MODE"
write_env LOCK_STATE "$LOCK_STATE"
write_env AUTHORIZATION "$AUTHORIZED"

# ── 3 ────────────────────────────────────────────────────────────────────
stage "Discovery and storage identity" 8
step "In Explorer, confirm the Odin appears under 'This PC'."
step "In ROM Manager, run device discovery."
ask DISCOVERY_RESULT "Device discovered (pass / FAIL):"
ask STORAGE_SEEN "Storage volumes offered (internal / sd-card / both):"
say "Record which storage this run targets — they behave differently."
ask STORAGE_UNDER_TEST "Storage under test (internal / sd-card):"
ask CAPACITY_REPORTED "Does it report free space? (yes / no):"
note "A device that does not report free space must BLOCK additions rather"
note "than guess. If it reports 'no' and additions still plan, that is a FAIL."
write_env DISCOVERY_RESULT "$DISCOVERY_RESULT"
write_env STORAGE_SEEN "$STORAGE_SEEN"
write_env STORAGE_UNDER_TEST "$STORAGE_UNDER_TEST"
write_env CAPACITY_REPORTED "$CAPACITY_REPORTED"
ask PROFILE_REVISION "Device Profile revision shown in the plan:"
ask FIXTURE_HASH "Fixture sha256 shown:"
write_env PROFILE_REVISION "$PROFILE_REVISION"
write_env FIXTURE_HASH "$FIXTURE_HASH"

# ── 4 ────────────────────────────────────────────────────────────────────
stage "Marker, add, and full read-back" 10
step "Initialize the target. Confirm it asks before claiming the device."
ask MARKER_INIT "Marker initialization required confirmation (pass / FAIL):"
step "Re-read the marker. It must come back exactly as written."
ask MARKER_READBACK "Marker read-back matches (pass / FAIL):"
step "Sync the fixture. Watch for a VERIFYING phase after the write."
ask ADD_READBACK "Add with full WPD read-back verification (pass / FAIL):"
step "Sync again unchanged. It must retain, not re-transfer."
ask RETAIN_RESULT "Retain without re-transfer (pass / FAIL):"
write_env MARKER_INITIALIZATION "$MARKER_INIT"
write_env MARKER_READBACK "$MARKER_READBACK"
write_env ADD_WITH_READBACK "$ADD_READBACK"
write_env RETAIN "$RETAIN_RESULT"

# ── 5 ────────────────────────────────────────────────────────────────────
stage "Adoption, conflict, capacity, removal" 12
step "Copy the fixture onto the device by hand, then plan."
ask ADOPTION_RESULT "Offered as adoption, NOT taken silently (pass / FAIL):"
step "Put a different file at a target path, then plan."
ask CONFLICT_RESULT "Blocked and your file kept (pass / FAIL):"
step "Fill the storage, then plan an addition."
ask CAPACITY_RESULT "Blocked before writing (pass / FAIL / n-a-no-capacity-reporting):"
step "Deselect a synced item and run the removal, acknowledging the count."
ask REMOVAL_RESULT "Permanent managed removal (pass / FAIL):"
write_env ADOPTION "$ADOPTION_RESULT"
write_env CANONICAL_CONFLICT "$CONFLICT_RESULT"
write_env CAPACITY_BLOCKING "$CAPACITY_RESULT"
write_env MANAGED_REMOVAL "$REMOVAL_RESULT"

# ── 6 ────────────────────────────────────────────────────────────────────
stage "Interrupt it — the cases MTP gets wrong" 15
warn "Unplug at each phase below. Record the TERMINAL STATE and RESIDUE."
warn "There must never be an automatic resume."
for CASE in unplug_during_scan unplug_during_write unplug_during_verify \
            unplug_during_publish unplug_during_delete cancel_mid_transfer; do
  case "$CASE" in
    unplug_during_scan)    step "Unplug while it is scanning the device." ;;
    unplug_during_write)   step "Unplug while a file is transferring." ;;
    unplug_during_verify)  step "Unplug during the verifying phase." ;;
    unplug_during_publish) step "Unplug while it writes the manifest." ;;
    unplug_during_delete)  step "Unplug during a removal." ;;
    cancel_mid_transfer)   step "Press cancel mid-transfer (no unplug)." ;;
  esac
  ask STATE "Terminal state (completed / cancelled / incomplete / indeterminate):"
  ask RESIDUE "Residue on the device (none / describe):"
  write_env "FAULT_${CASE^^}_STATE" "$STATE"
  write_env "FAULT_${CASE^^}_RESIDUE" "$RESIDUE"
  if confirm "Did it resume automatically, or claim success it could not support?"; then
    write_env "FAULT_${CASE^^}_VERDICT" "FAIL-UNSAFE"
    warn "Recorded as UNSAFE. This blocks the milestone."
  else
    write_env "FAULT_${CASE^^}_VERDICT" "safe"
  fi
  step "Now reconnect, refresh, and build a NEW plan before continuing."
done

# ── 7 ────────────────────────────────────────────────────────────────────
stage "Reconnect, locking, and awkward names" 8
step "Unplug and replug, ideally into a different USB port."
ask LOCATOR_CHANGE "Identity unchanged across a new locator (pass / FAIL):"
step "Lock the Odin's screen, then try to refresh from the app."
ask LOCKED_DEVICE "Locked device reported clearly, not as an error blob (pass / FAIL):"
say "MTP allows two objects with the same name in one folder."
step "If you can create a duplicate name on the device, do so, then plan."
ask AMBIGUOUS_NAMES "Ambiguity refused rather than guessed (pass / FAIL / could-not-test):"
step "Try a ROM whose name uses non-ASCII characters, and a nested folder."
ask UNICODE_PATHS "Unicode names handled (pass / FAIL / could-not-test):"
ask NESTED_PATHS "Nested paths handled (pass / FAIL / could-not-test):"
write_env LOCATOR_CHANGE "$LOCATOR_CHANGE"
write_env LOCKED_DEVICE "$LOCKED_DEVICE"
write_env AMBIGUOUS_NAMES "$AMBIGUOUS_NAMES"
write_env UNICODE_PATHS "$UNICODE_PATHS"
write_env NESTED_PATHS "$NESTED_PATHS"

# ── 8 ────────────────────────────────────────────────────────────────────
stage "Cross-check the card against a reader" 4
say "The same SD card seen two ways is the strongest evidence available:"
say "if WPD and a card reader disagree, WPD is lying about something."
if confirm "Do you have a card reader and a removable card in the Odin?"; then
  step "Eject the card, read it in the card reader, compare the managed folder."
  ask CARD_CROSSCHECK "Contents agree between WPD and card reader (pass / FAIL):"
  ask CARD_FILESYSTEM "Filesystem on the card (exFAT / FAT32 / other):"
else
  CARD_CROSSCHECK=not-possible
  CARD_FILESYSTEM=n-a
  note "Recorded as not possible with this hardware."
fi
write_env CARD_READER_CROSSCHECK "$CARD_CROSSCHECK"
write_env CARD_FILESYSTEM "$CARD_FILESYSTEM"

ask FIRMWARE_LIMITATIONS "Any firmware or device limitations worth recording:"
write_env FIRMWARE_LIMITATIONS "$FIRMWARE_LIMITATIONS"

finish
note "Results recorded in $ENV_FILE"
note "Attach it, plus logs, to issue #38 and link from the milestone report."
