#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Validation runbook for issue #77 — the Linux AppImage on real hosts.
#
# Run this on the Linux host under test. It records observations into a results
# file the milestone evidence links. It does not decide anything passed.

ENV_FILE="${ENV_FILE:-docs/validation/linux-parity/results.env}"
mkdir -p "$(dirname "$ENV_FILE")"

TOTAL_STAGES=7
TOTAL_MINUTES=55

banner "Validate the Linux AppImage (#77)"

# ── 1 ────────────────────────────────────────────────────────────────────
stage "Identify the build and host" 6
ask APPIMAGE_PATH "Path to the .AppImage under test:"
if [[ -f "$APPIMAGE_PATH" ]]; then
  APPIMAGE_SHA=$(sha256sum "$APPIMAGE_PATH" | cut -d' ' -f1)
  say "sha256: $APPIMAGE_SHA"
else
  warn "not found — record the hash by hand"
  ask APPIMAGE_SHA "AppImage sha256:"
fi
ask BUILD_COMMIT "Commit it was built from:"
step "Run: cat /etc/os-release | head -2"
ask DISTRO "Distribution and version:"
ask DESKTOP "Desktop environment (GNOME / KDE / other):"
write_env APPIMAGE_SHA256 "$APPIMAGE_SHA"
write_env BUILD_COMMIT "$BUILD_COMMIT"
write_env DISTRO "$DISTRO"
write_env DESKTOP "$DESKTOP"

# ── 2 ────────────────────────────────────────────────────────────────────
stage "Clean-host launch" 8
say "A clean host means no previous install and no ~/.local/share/rom-manager."
step "Run: chmod +x \"$APPIMAGE_PATH\" && \"$APPIMAGE_PATH\""
ask LAUNCH_RESULT "Launched on a clean host (pass / FAIL):"
if [[ "$LAUNCH_RESULT" == "FAIL" ]]; then
  ask LAUNCH_NOTE "What happened?"
  write_env LAUNCH_FAILURE "$LAUNCH_NOTE"
fi
step "Confirm data landed under ~/.local/share/rom-manager (not inside the mount)."
ask DATA_LOCATION "Application data location observed:"
step "Check nothing was written under /tmp/.mount_* — that vanishes on exit."
ask MOUNT_CLEAN "Nothing written into the AppImage mount (pass / FAIL):"
write_env CLEAN_LAUNCH "$LAUNCH_RESULT"
write_env DATA_LOCATION "$DATA_LOCATION"
write_env MOUNT_NOT_WRITTEN "$MOUNT_CLEAN"

# ── 3 ────────────────────────────────────────────────────────────────────
stage "Offline operation" 5
say "Disconnect the network entirely — pull the cable, disable Wi-Fi."
step "With no network, run a complete import and sync."
ask OFFLINE_RESULT "Full workflow with no network (pass / FAIL):"
if [[ "$OFFLINE_RESULT" == "FAIL" ]]; then
  ask OFFLINE_NOTE "What did it try to reach, or fail at?"
  write_env OFFLINE_FAILURE "$OFFLINE_NOTE"
fi
write_env OFFLINE_OPERATION "$OFFLINE_RESULT"

# ── 4 ────────────────────────────────────────────────────────────────────
stage "Filesystem coverage" 14
warn "Each filesystem needs a REAL volume — formatting a USB stick is fine."
for FS in ext4 exfat fat32; do
  case "$FS" in
    ext4)  step "Sync to an ext4 volume. This is the baseline." ;;
    exfat) step "Sync to an exFAT volume — the common SD-card format." ;;
    fat32) step "Attempt a sync to a FAT32 volume. It must BLOCK with a reason." ;;
  esac
  ask RESULT "Result for $FS (pass / FAIL / blocked-as-expected / n-a):"
  write_env "FS_${FS^^}" "$RESULT"
  if [[ "$FS" == "fat32" ]]; then
    say "The block must name the 4 GiB limit and the case-handling risk."
    ask FAT32_REASON "Reason shown to the user:"
    write_env FAT32_REASON "$FAT32_REASON"
  fi
done

# ── 5 ────────────────────────────────────────────────────────────────────
stage "Mounted network share" 6
say "SMB is supported only when the host OS has mounted it — the application"
say "speaks no SMB of its own."
if confirm "Do you have an SMB share you can mount?"; then
  step "Mount it through your file manager or: sudo mount -t cifs ..."
  step "Select the mounted path as a Media Target and sync."
  ask SMB_RESULT "Mounted-SMB sync (pass / FAIL):"
  ask SMB_NOTE "Anything surprising (locking, permissions, speed):"
  write_env SMB_NOTE "$SMB_NOTE"
else
  SMB_RESULT=not-tested
  note "Recorded as not tested."
fi
write_env SMB_SYNC "$SMB_RESULT"

# ── 6 ────────────────────────────────────────────────────────────────────
stage "Accessibility on the packaged app" 10
step "Unplug the mouse. Complete the whole workflow by keyboard alone."
ask A11Y_KEYBOARD "Keyboard-only completion (pass / FAIL):"
step "Watch the focus ring at every step."
ask A11Y_FOCUS "Focus always visible (pass / FAIL):"
step "Enable Orca (GNOME) or your screen reader; check plan and result announcements."
ask A11Y_ANNOUNCE "Announcements adequate (pass / FAIL):"
step "Set display scaling to 200% and repeat the core workflow."
ask A11Y_SCALING "Usable at 100% and 200%, no horizontal scrolling (pass / FAIL):"
ask A11Y_CONTRAST "Contrast meets WCAG 2.2 AA (pass / FAIL / not-measured):"
write_env A11Y_KEYBOARD "$A11Y_KEYBOARD"
write_env A11Y_FOCUS "$A11Y_FOCUS"
write_env A11Y_ANNOUNCEMENTS "$A11Y_ANNOUNCE"
write_env A11Y_SCALING "$A11Y_SCALING"
write_env A11Y_CONTRAST "$A11Y_CONTRAST"

# ── 7 ────────────────────────────────────────────────────────────────────
stage "Upgrade and removal" 6
warn "Removal MUST NOT delete the Library or database."
step "Replace the AppImage with a newer build and launch it."
ask UPGRADE_RESULT "Upgrade preserved data (pass / FAIL / n-a):"
step "Delete the AppImage file. Then check ~/.local/share/rom-manager still exists."
ask REMOVAL_RESULT "Removal left the Library intact (pass / FAIL):"
write_env UPGRADE_PRESERVES_DATA "$UPGRADE_RESULT"
write_env REMOVAL_PRESERVES_DATA "$REMOVAL_RESULT"

finish
note "Results recorded in $ENV_FILE"
note "Run this on BOTH current Ubuntu LTS and current Fedora GNOME, then attach"
note "both result files to issue #77."
