#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Validation runbook for issue #37 — the packaged filesystem tracer on Windows.
#
# Run this on the Windows host itself, in Git Bash. It records the environment
# and every observation into a results file that the milestone report links.
#
# It deliberately does NOT tell you a case passed. You observe, you record.

ENV_FILE="${ENV_FILE:-docs/validation/windows-sync-core/windows-filesystem-results.env}"
mkdir -p "$(dirname "$ENV_FILE")"

TOTAL_STAGES=9
TOTAL_MINUTES=75

banner "Validate the packaged filesystem tracer on Windows (#37)"

# ── 1 ────────────────────────────────────────────────────────────────────
stage "Identify the exact build" 5
say "Every result below is only meaningful against one exact installer."
step "Copy the installer you are about to test into this folder."
ask INSTALLER_PATH "Path to the .exe installer:"
if [[ -f "$INSTALLER_PATH" ]]; then
  INSTALLER_SHA=$(sha256sum "$INSTALLER_PATH" | cut -d' ' -f1)
  say "sha256: $INSTALLER_SHA"
else
  warn "not found — record the hash by hand"
  ask INSTALLER_SHA "Installer sha256:"
fi
ask BUILD_COMMIT "Commit the installer was built from:"
write_env INSTALLER_SHA256 "$INSTALLER_SHA"
write_env BUILD_COMMIT "$BUILD_COMMIT"

# ── 2 ────────────────────────────────────────────────────────────────────
stage "Record the host" 5
step "Run: cmd /c ver     (Windows version)"
ask WINDOWS_VERSION "Windows version string:"
ask WINDOWS_ARCH "Architecture (x64 / arm64):"
say "A clean host means no previous ROM Manager install and no leftover data."
if confirm "Is this a clean host?"; then CLEAN_HOST=yes; else CLEAN_HOST=no; fi
write_env WINDOWS_VERSION "$WINDOWS_VERSION"
write_env WINDOWS_ARCH "$WINDOWS_ARCH"
write_env CLEAN_HOST "$CLEAN_HOST"

# ── 3 ────────────────────────────────────────────────────────────────────
stage "Record the storage under test" 8
say "The gate needs NTFS *and* representative removable storage."
ask STORAGE_KIND "Storage kind (internal-ntfs / usb-stick / sd-card):"
step "Run: fsutil fsinfo volumeinfo <drive>:"
ask STORAGE_FILESYSTEM "Filesystem reported (NTFS / exFAT / FAT32):"
ask STORAGE_LABEL "Volume label or device description:"
note "exFAT and FAT32 are where filesystem assumptions break first — if you"
note "have a card formatted that way, it is worth more than a second NTFS run."
write_env STORAGE_KIND "$STORAGE_KIND"
write_env STORAGE_FILESYSTEM "$STORAGE_FILESYSTEM"
write_env STORAGE_LABEL "$STORAGE_LABEL"

# ── 4 ────────────────────────────────────────────────────────────────────
stage "Install, launch, and confirm offline operation" 10
step "Run the installer. Accept the default (per-machine) location."
step "Launch ROM Manager and let it reach its first screen."
say "Now disconnect the network entirely — pull the cable, disable Wi-Fi."
step "With the network down, exercise the whole workflow once."
if confirm "Did the application work fully with no network?"; then
  OFFLINE_OK=pass
else
  OFFLINE_OK=FAIL
  ask OFFLINE_NOTE "What did it try to do or fail at?"
  write_env OFFLINE_FAILURE_NOTE "$OFFLINE_NOTE"
fi
step "Find the app data folder (usually %APPDATA%\\dev.mill1893.rom-manager)."
ask APPDATA_PATH "Application data location:"
write_env OFFLINE_OPERATION "$OFFLINE_OK"
write_env APPDATA_PATH "$APPDATA_PATH"

# ── 5 ────────────────────────────────────────────────────────────────────
stage "Record the fixture and profile identity" 4
step "In the app, open the sync plan and read the identity fields."
ask PROFILE_REVISION "Device Profile revision shown:"
ask FIXTURE_HASH "Fixture sha256 shown (or from fixtures/nes/tracers.sha256):"
write_env PROFILE_REVISION "$PROFILE_REVISION"
write_env FIXTURE_HASH "$FIXTURE_HASH"

# ── 6 ────────────────────────────────────────────────────────────────────
stage "Exercise the normal workflow" 12
say "Record what you observe, not what you expect."
for CASE in add_readback retain adoption conflict; do
  case "$CASE" in
    add_readback) step "Sync the fixture to an empty managed folder. Confirm the file lands and verifies." ;;
    retain)       step "Sync again with no changes. It should retain, not re-copy." ;;
    adoption)     step "Copy the fixture in by hand, then plan. It should OFFER adoption, not take it silently." ;;
    conflict)     step "Put a DIFFERENT file at the target path, then plan. It must block and keep your file." ;;
  esac
  ask RESULT "Result for $CASE (pass / FAIL / blocked / n-a):"
  write_env "CASE_${CASE^^}" "$RESULT"
  if [[ "$RESULT" == "FAIL" ]]; then
    ask NOTE "What happened?"
    write_env "CASE_${CASE^^}_NOTE" "$NOTE"
  fi
done

# ── 7 ────────────────────────────────────────────────────────────────────
stage "Inject faults — the part that matters" 18
warn "For each: record the TERMINAL STATE and any RESIDUE left behind."
warn "A case that reports success it cannot support is a FAIL, even if the"
warn "files happen to be correct."
for CASE in insufficient_capacity cancellation disconnect changed_locator \
            marker_conflict target_mutation manifest_disagreement refresh_recovery; do
  case "$CASE" in
    insufficient_capacity) step "Fill the device so the plan cannot fit. Plan must block BEFORE writing." ;;
    cancellation)          step "Start a sync and cancel mid-transfer." ;;
    disconnect)            step "Start a sync and physically unplug the device mid-write." ;;
    changed_locator)       step "Reconnect at a different drive letter. Identity must NOT change." ;;
    marker_conflict)       step "Edit ROMManager/target.json to a different id. Must block, never rewrite." ;;
    target_mutation)       step "Build a plan, then change the device before executing it." ;;
    manifest_disagreement) step "Corrupt ROMManager/manifest.json. Destructive actions must block." ;;
    refresh_recovery)      step "After any fault above: refresh, build a NEW plan, and complete it." ;;
  esac
  ask STATE "Terminal state (completed / cancelled / incomplete / indeterminate / blocked):"
  ask RESIDUE "Residue left behind (none / describe):"
  write_env "FAULT_${CASE^^}_STATE" "$STATE"
  write_env "FAULT_${CASE^^}_RESIDUE" "$RESIDUE"
  if confirm "Did this case report success it could not support, or remove something unverified?"; then
    write_env "FAULT_${CASE^^}_VERDICT" "FAIL-UNSAFE"
    warn "Recorded as UNSAFE. This blocks the milestone."
  else
    write_env "FAULT_${CASE^^}_VERDICT" "safe"
  fi
done

# ── 8 ────────────────────────────────────────────────────────────────────
stage "Accessibility on the packaged app" 8
say "These are the checks jsdom cannot make — they need real layout."
step "Unplug the mouse. Complete the whole workflow with the keyboard alone."
ask A11Y_KEYBOARD "Keyboard-only completion (pass / FAIL):"
step "Watch the focus ring through every step. It must always be visible."
ask A11Y_FOCUS "Focus always visible (pass / FAIL):"
step "Turn on Narrator. Confirm the plan, blockers, and result are announced."
ask A11Y_ANNOUNCE "Announcements adequate (pass / FAIL):"
step "Set display scaling to 200% (Settings → Display → Scale)."
ask A11Y_SCALING "Usable at 100% and 200% (pass / FAIL):"
step "Check text contrast against WCAG 2.2 AA (4.5:1 body, 3:1 large)."
ask A11Y_CONTRAST "Contrast meets AA (pass / FAIL / not-measured):"
write_env A11Y_KEYBOARD "$A11Y_KEYBOARD"
write_env A11Y_FOCUS "$A11Y_FOCUS"
write_env A11Y_ANNOUNCEMENTS "$A11Y_ANNOUNCE"
write_env A11Y_SCALING "$A11Y_SCALING"
write_env A11Y_CONTRAST "$A11Y_CONTRAST"

# ── 9 ────────────────────────────────────────────────────────────────────
stage "Upgrade, uninstall, reinstall" 5
warn "Uninstall MUST NOT delete the user's library or operation history."
step "Install the newer build over the top. Confirm data survives."
ask UPGRADE_RESULT "Upgrade preserved data (pass / FAIL / n-a):"
step "Uninstall. Then check the app data folder still exists."
ask UNINSTALL_RESULT "Uninstall left data intact (pass / FAIL):"
step "Reinstall and launch. Confirm the previous library is still there."
ask REINSTALL_RESULT "Reinstall found existing data (pass / FAIL):"
write_env UPGRADE_PRESERVES_DATA "$UPGRADE_RESULT"
write_env UNINSTALL_PRESERVES_DATA "$UNINSTALL_RESULT"
write_env REINSTALL_FINDS_DATA "$REINSTALL_RESULT"

finish
note "Results recorded in $ENV_FILE"
note "Attach it, plus any logs, to issue #37 and link from the milestone report."
